name: "EasyWallbox"
description: "Free2Move Wallbox Integration"
author: "Roman Nawrot"
version: "1.0.6"
slug: "easywallbox"
init: false
arch:
  - aarch64
  - amd64
  - armv7
startup: application
boot: auto
options:
  wallbox_address: ""
  wallbox_pin: "0000"
  mqtt_host: "core-mosquitto"
  mqtt_port: 1883
  mqtt_username: ""
  mqtt_password: ""
  mqtt_topic: "easywallbox"
schema:
  wallbox_address: str
  wallbox_pin: str
  mqtt_host: str
  mqtt_port: int
  mqtt_username: str
  mqtt_password: str
  mqtt_topic: str
host_network: true
privileged:
  - NET_ADMIN
host_dbus: true

